// Code generated by go-swagger; DO NOT EDIT.

// Package restapi App authentication
//
//  Reseaching about authentication flow
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <msgtosuriya@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
