// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"go-auth-flow/internal/config"
)

// Injectors from wire.go:

func GetApp(ctx context.Context) (*App, error) {
	configuration := config.GetConfiguration()
	appConfiguration := &config.AppConfiguration{
		Configuration: configuration,
	}
	app := &App{
		AppConfig: appConfiguration,
	}
	return app, nil
}

// wire.go:

type App struct {
	AppConfig *config.AppConfiguration
}
