// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/google/wire"
	"oauth-study/handlers"
)

// Injectors from wire.go:

func GetApp(ctx context.Context) (*App, error) {
	loginHandler := handlers.LoginHandler{}
	app := &App{
		LoginHandler: loginHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	LoginHandler handlers.LoginHandler
}

var handlerSet = wire.NewSet(wire.Struct(new(handlers.LoginHandler), "*"))
